language: ruby
rvm:
- 2.2
script:
- gem install yamlandar
- yamlandar -c > index.html
after_success:
- bash deploy.sh ga-dc/wdi12
env:
  global:
    secure: qw6Dv3eo9+nwF/GaHRAqLPAMNaSIKkZBdM2OlwfmhdklS0xmWrgYhEz3ylE9b11jbiIvL14m62xd6w1GYAivHU8OMrFK6v5HsR0Ii3c7Aoc4+3o5mewtW8sKw01Yf1zcVArGEe5A2pfj5iuNIfLf+Ic1lx+N9XMCVGKeviVMDohGYL+VTUe3sbulM6EFEFittCwdyYAwyQZ1LUfzb6jvQY2Ss4kqXc23yS9yip31zfxoHb8NFKaMmQXQJ3f+1Gf/2Nkuz0s3za3PxdCqPgfTc7SzuldVgbZUMOk21HZoFFys9ruvypYrXtspzOItx2UhL8yzQN5KhKuG9tm6erf0p21AZUI7zZOQUZk6Zszew852mf8H3dTcOjWk/gK5LfhlaMOSQJrUVVaO2G6SZrwmdz/Y1PwIpRFvqAlOGBIM6xRrK6QglIIUUKElJi9GzqzA/YVc4P7NUu9ZDST6VsSUw2/aNT0Ocxkt7+UVLXo62gmuAEYtgmE7RtTSIkvCRXa7iJBEzx/vNd9r+hUbZtiK31KDrPjQWkskqukA0oMJd0m8ybqL6/xG7hc9nhxIUh7BPb5aoq6R6+Vsy3WmVA/I9cNwtG6ufh7U7EB7Yx07G75SNSoYekc4GBjQaPDREF+904kVw7CYsbY5yOe7Z2kQXL+UcMl33Hq2LXaFlul8LYY=
